baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Aured's Site"
theme = 'ananke'
sectionPagesMenu = 'main'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'About'
    pageRef = '/about/'
    weight = 20
  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts/'
    weight = 30